"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { IncomingCall as IncomingCallData, Customer } from "@/lib/engine/types";

export default function IncomingCallOverlay({
  call,
  customer,
  onFinished,
}: {
  call: IncomingCallData;
  customer?: Customer;
  onFinished: () => void;
}) {
  const [phase, setPhase] = useState<"ringing" | "talking" | "ended" | "reveal">("ringing");
  const [visibleChars, setVisibleChars] = useState(0);
  const played = useRef(false);

  const spoken = useMemo(() => call.script, [call.script]);

  useEffect(() => {
    if (phase !== "talking") return;
    setVisibleChars(0);
    const id = window.setInterval(() => {
      setVisibleChars((count) => {
        if (count >= spoken.length) {
          window.clearInterval(id);
          return count;
        }
        return count + 2;
      });
    }, 18);
    return () => window.clearInterval(id);
  }, [phase, spoken.length]);

  async function playVoice() {
    if (played.current) return;
    played.current = true;
    try {
      const response = await fetch("/api/voice", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text: spoken }),
      });
      const type = response.headers.get("content-type") ?? "";
      if (type.includes("audio")) {
        const blob = await response.blob();
        const url = URL.createObjectURL(blob);
        const audio = new Audio(url);
        audio.onended = () => setPhase("ended");
        await audio.play();
        return;
      }
    } catch {
      /* browser voice fallback */
    }
    if ("speechSynthesis" in window) {
      const utter = new SpeechSynthesisUtterance(spoken);
      utter.rate = 0.92;
      utter.pitch = 0.92;
      utter.onend = () => setPhase("ended");
      window.speechSynthesis.speak(utter);
      return;
    }
    setTimeout(() => setPhase("ended"), 8000);
  }

  async function answer() {
    setPhase("talking");
    const failSafe = window.setTimeout(() => {
      setPhase((current) => (current === "talking" ? "ended" : current));
    }, 14000);
    await playVoice();
    window.setTimeout(() => window.clearTimeout(failSafe), 16000);
  }

  return (
    <div className="fixed inset-0 z-40 flex items-center justify-center bg-black/80 px-6">
      <div className="relative w-full max-w-2xl overflow-hidden rounded-3xl border border-white/10 bg-[#12090b] p-8 shadow-call sm:p-12">
        <div className="pointer-events-none absolute -right-16 -top-16 h-56 w-56 rounded-full bg-signal/20 blur-3xl" />
        <p className="kicker text-signal">Incoming call — day {call.day}</p>

        {phase === "ringing" && (
          <div className="mt-10 flex flex-col items-center text-center">
            <div className="relative mb-8 grid h-28 w-28 place-items-center">
              <span className="pulse-ring absolute inset-0 rounded-full border border-signal/70" />
              <span className="pulse-ring absolute inset-0 rounded-full border border-signal/40 [animation-delay:400ms]" />
              <span className="ring-phone grid h-16 w-16 place-items-center rounded-full bg-signal text-ink-950">
                <PhoneIcon />
              </span>
            </div>
            <p className="font-serif text-4xl tracking-tight">{call.fromName}</p>
            <p className="mt-2 text-paper/60">
              {customer?.title ?? "Customer"} · {call.fromCompany}
            </p>
            <p className="mt-1 font-mono text-xs tracking-widest text-paper/35">
              TENURE {call.tenureLabel.toUpperCase()}
            </p>
            <button
              onClick={answer}
              className="mt-10 rounded-full bg-mint px-8 py-3 text-sm font-medium tracking-wide text-ink-950"
            >
              Answer
            </button>
          </div>
        )}

        {phase === "talking" && (
          <div className="mt-8">
            <p className="font-serif text-3xl leading-snug text-paper">
              {spoken.slice(0, visibleChars)}
              <span className="inline-block w-2 animate-pulse bg-signal align-middle">&nbsp;</span>
            </p>
            <p className="mt-8 font-mono text-xs tracking-widest text-paper/40">LIVE · SYNTHETIC LINE</p>
          </div>
        )}

        {(phase === "ended" || phase === "reveal") && (
          <div className="mt-8">
            <p className="font-serif text-2xl leading-snug text-paper/80 sm:text-3xl">{spoken}</p>
            <div className="mt-10 hairline" />
            <p className="mt-8 font-serif text-4xl italic text-ember-400 sm:text-5xl">
              {call.closingLine}
            </p>
            <p className="mt-4 max-w-lg text-sm leading-relaxed text-paper/55">
              They are a synthetic customer generated by AFTERMATH from a possible future created by the proposed decision.
            </p>
            <button
              onClick={onFinished}
              className="mt-10 rounded-full border border-white/20 px-6 py-3 text-sm tracking-wide text-paper hover:border-ember-400"
            >
              See the rest of this future
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

function PhoneIcon() {
  return (
    <svg width="26" height="26" viewBox="0 0 24 24" fill="none" aria-hidden>
      <path
        d="M7 3.5h3.2l1 4.2-2 1.2a12.5 12.5 0 0 0 5.9 5.9l1.2-2 4.2 1V18a2 2 0 0 1-2.2 2A16.5 16.5 0 0 1 4 5.7 2 2 0 0 1 6 3.5H7Z"
        fill="currentColor"
      />
    </svg>
  );
}
